"""Evidence engine (spec §18).

Stores per-finding evidence as sanitized JSON files under EVIDENCE_DIR and
masks every sensitive value before persisting: Authorization/Cookie/API-key
headers, tokens, passwords and common secret shapes.
"""
from __future__ import annotations

import json
import re
import tempfile
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from ..config import settings

MAX_BODY_BYTES = 4096
MASK = "********"

_SENSITIVE_HEADERS = frozenset(
    {
        "authorization",
        "cookie",
        "set-cookie",
        "x-api-key",
        "x-auth-token",
        "x-access-token",
        "x-session-token",
        "proxy-authorization",
        "x-csrf-token",
        "x-xsrf-token",
        "x-csrftoken",
        "cookie2",
    }
)

_SECRET_BODY_PATTERNS: list[re.Pattern[str]] = [
    re.compile(r"""(?i)("[^"]*password[^"]*"\s*[:=]\s*)("[^"]{1,200}"|'[^']{1,200}'|[^\s,&\";]{4,200})"""),
    re.compile(r"""(?i)("[^"]*token[^"]*"\s*[:=]\s*)("?[A-Za-z0-9._\-]{8,200}"?)"""),
    re.compile(r"""(?i)("[^"]*api[_-]?key[^"]*"\s*[:=]\s*)("?[A-Za-z0-9._\-]{8,200}"?)"""),
    re.compile(r"""(?i)(password\s*[:=]\s*)([^\s&\"';,]{4,200})"""),
    re.compile(r"(AKIA[0-9A-Z]{16})"),
    re.compile(r"(gh[pousr]_[A-Za-z0-9]{20,})"),
    re.compile(r"(sk-[A-Za-z0-9]{20,})"),
    re.compile(r"(sk-proj-[A-Za-z0-9_-]{20,})"),
    re.compile(r"(-----BEGIN [A-Z ]*PRIVATE KEY-----)[\s\S]*?(-----END [A-Z ]*PRIVATE KEY-----)"),
    re.compile(r"(?i)(bearer\s+)([A-Za-z0-9_\-]+\.[A-Za-z0-9_\-]+\.[A-Za-z0-9_\-]+)"),
]

# Assessment ID must be the hex UUID generated by the platform – prevents
# directory-traversal via a crafted assessment_id.
_ASSESSMENT_ID_RE = re.compile(r"^[a-fA-F0-9]{16,64}$")


def _sanitize_assessment_id(aid: str) -> str:
    if not isinstance(aid, str) or not aid:
        raise ValueError("assessment_id must be a non-empty string")
    if "\x00" in aid or "/" in aid or "\\" in aid or ".." in aid:
        raise ValueError("assessment_id contains illegal characters")
    # Allow the standard 32-hex id plus longer variants; fallback to safe check
    if not _ASSESSMENT_ID_RE.match(aid):
        # Also allow UUID with hyphens for compatibility – strip hyphens then check
        stripped = aid.replace("-", "")
        if not re.fullmatch(r"[a-fA-F0-9]{16,64}", stripped):
            raise ValueError(f"assessment_id '{aid}' has invalid format")
        # Normalize to stripped hex to avoid filesystem issues with hyphens
        return stripped
    return aid


def mask_headers(headers: dict[str, str] | list[tuple[str, str]] | None) -> dict[str, str]:
    """Mask sensitive header values, preserving auth scheme prefix when present."""
    if headers is None:
        return {}
    items = headers.items() if isinstance(headers, dict) else headers  # type: ignore[arg-type]
    masked: dict[str, str] = {}
    for name, value in items:  # type: ignore[misc]
        key = str(name)
        low = key.lower()
        val_str = str(value) if value is not None else ""
        if low in _SENSITIVE_HEADERS:
            # Preserve scheme prefix case-insensitively (Bearer/Basic)
            prefix = ""
            lower_val = val_str.lower()
            for scheme in ("bearer ", "basic "):
                if lower_val.startswith(scheme):
                    # Preserve original casing of the scheme as it appeared
                    prefix = val_str[: len(scheme)]
                    break
            masked[key] = f"{prefix}{MASK}"
        else:
            masked[key] = val_str
    return masked


def mask_text(text: str) -> str:
    """Mask captured secret portions while keeping key/prefix context."""
    if not isinstance(text, str):
        text = str(text) if text is not None else ""
    out = text or ""
    for pattern in _SECRET_BODY_PATTERNS:
        def _sub(match: re.Match[str]) -> str:
            ngroups = pattern.groups
            if ngroups >= 2:
                # Keep the key/prefix (group 1), replace the secret (group 2 onward)
                # For private-key block we have two groups: begin and end – replace middle
                if ngroups == 2 and "PRIVATE KEY" in (match.group(1) or ""):
                    return f"{match.group(1)}{MASK}{match.group(2)}"
                return f"{match.group(1)}{MASK}"
            return MASK

        try:
            out = pattern.sub(_sub, out)
        except re.error:
            continue
    return out


def mask_body(body: str | bytes | None) -> str:
    """Decode, truncate, and mask a request/response body excerpt."""
    if body is None:
        return ""
    if isinstance(body, bytes):
        try:
            body = body.decode("utf-8", errors="replace")
        except Exception:
            body = body.decode("latin-1", errors="replace")
    if not isinstance(body, str):
        body = str(body)
    # Truncate to byte budget before masking to bound work; slice on chars is close enough
    # but ensure we don't split a surrogate in a way that breaks masking.
    truncated = body[:MAX_BODY_BYTES]
    return mask_text(truncated)


class EvidenceStore:
    """Per-assessment evidence writer with anti-overwrite and atomic-write guarantees."""

    def __init__(self, assessment_id: str):
        safe_id = _sanitize_assessment_id(assessment_id)
        # Resolve EVIDENCE_DIR to an absolute path to make relative_to robust
        evidence_root = Path(settings.EVIDENCE_DIR).resolve()
        self.dir = evidence_root / safe_id
        self.dir.mkdir(parents=True, exist_ok=True)
        # Tighten permissions on the evidence directory (best effort, ignore on Windows)
        try:
            self.dir.chmod(0o700)
        except Exception:
            pass
        self.assessment_id = safe_id
        self._evidence_root = evidence_root
        self._counter = self._initial_counter()

    def _initial_counter(self) -> int:
        """Start after the highest existing evidence_*.json index to avoid overwrites."""
        try:
            existing = list(self.dir.glob("evidence_*.json"))
        except Exception:
            return 0
        max_n = 0
        for p in existing:
            m = re.match(r"evidence_(\d+)\.json$", p.name)
            if m:
                try:
                    n = int(m.group(1))
                    if n > max_n:
                        max_n = n
                except ValueError:
                    continue
        return max_n

    def _next_path(self) -> Path:
        """Return the next non-existing evidence file path (atomic counter)."""
        # Increment until we find a free slot – handles concurrent callers and
        # retest stores that start after a prior run.
        for _ in range(10000):
            self._counter += 1
            candidate = self.dir / f"evidence_{self._counter:04d}.json"
            if not candidate.exists():
                return candidate
        # Fallback to UUID-based name if we somehow exhaust the counter range
        import uuid as _uuid

        return self.dir / f"evidence_{_uuid.uuid4().hex[:8]}.json"

    def save(
        self,
        kind: str,
        payload: dict[str, Any],
        summary: str = "",
    ) -> dict[str, str]:
        """Persist a sanitized evidence document; returns {id,path,...} metadata."""
        if not isinstance(kind, str) or not kind.strip():
            raise ValueError("Evidence kind must be a non-empty string")
        if not isinstance(payload, dict):
            raise ValueError("Evidence payload must be a dict")
        kind = kind.strip()[:64]
        # Limit payload size to avoid disk exhaustion
        # Quick size check via json dumps length
        try:
            payload_json = json.dumps(payload, ensure_ascii=False)
            if len(payload_json) > 2 * 1024 * 1024:  # 2 MiB cap
                payload = {"truncated": True, "original_keys": list(payload.keys())[:20]}
        except (TypeError, ValueError):
            payload = {"error": "unserializable payload", "repr": str(payload)[:2000]}

        ts = datetime.now(timezone.utc).isoformat()
        doc: dict[str, Any] = {"kind": kind, "captured_at": ts, **payload}
        path = self._next_path()
        # Atomic write via temp file + rename
        tmp_path: Path | None = None
        try:
            # Create temp file in the same directory to ensure same filesystem
            fd, tmp_name = tempfile.mkstemp(dir=str(self.dir), prefix=".tmp_evidence_", suffix=".json")
            tmp_path = Path(tmp_name)
            with open(fd, "w", encoding="utf-8") as fh:
                json.dump(doc, fh, indent=2, ensure_ascii=False)
            # Ensure data is flushed to disk before rename
            try:
                fh.flush()
            except Exception:
                pass
            tmp_path.replace(path)
            try:
                path.chmod(0o600)
            except Exception:
                pass
        except Exception as exc:
            # Clean up temp file on failure
            if tmp_path and tmp_path.exists():
                try:
                    tmp_path.unlink()
                except Exception:
                    pass
            raise IOError(f"Failed to write evidence file: {exc}") from exc

        # Compute path relative to EVIDENCE_DIR for DB storage (portable, no absolute)
        try:
            rel = str(path.resolve().relative_to(self._evidence_root)).replace("\\", "/")
        except ValueError:
            # Fallback: relative to configured dir without resolve
            try:
                rel = str(path.relative_to(self._evidence_root)).replace("\\", "/")
            except ValueError:
                rel = str(path).replace("\\", "/")
        return {"path": rel, "kind": kind, "summary": summary or kind}

    def save_http_exchange(
        self,
        method: str,
        url: str,
        request_headers: dict[str, str] | None = None,
        request_body: str | bytes | None = None,
        status_code: int | None = None,
        response_headers: dict[str, str] | list[tuple[str, str]] | None = None,
        response_body: str | bytes | None = None,
        note: str = "",
    ) -> dict[str, str]:
        if not isinstance(method, str) or not method.strip():
            raise ValueError("HTTP method must be a non-empty string")
        if not isinstance(url, str) or not url.strip():
            raise ValueError("HTTP URL must be a non-empty string")
        # Validate status_code range if provided
        if status_code is not None and not (100 <= int(status_code) <= 599):
            status_code = None
        return self.save(
            kind="http_exchange",
            summary=note or f"{method.strip().upper()} {url.strip()} -> {status_code}",
            payload={
                "request": {
                    "method": method.strip().upper(),
                    "url": url.strip()[:2048],
                    "headers": mask_headers(request_headers or {}),
                    "body_excerpt": mask_body(request_body),
                },
                "response": {
                    "status_code": status_code,
                    "headers": mask_headers(response_headers or {}),
                    "body_excerpt": mask_body(response_body),
                },
            },
        )

    def save_scanner_output(self, scanner: str, raw_output: str | dict[str, Any], note: str = "") -> dict[str, str]:
        if not isinstance(scanner, str) or not scanner.strip():
            raise ValueError("Scanner name must be a non-empty string")
        scanner = scanner.strip()[:64]
        if isinstance(raw_output, dict):
            try:
                text = json.dumps(raw_output, indent=2, ensure_ascii=False)
            except (TypeError, ValueError):
                text = str(raw_output)
        elif isinstance(raw_output, str):
            text = raw_output
        else:
            text = str(raw_output)
        # Truncate before masking to bound CPU
        excerpt = mask_text(text[:MAX_BODY_BYTES])
        return self.save(
            kind="scanner_output",
            summary=note or f"{scanner} raw output",
            payload={"scanner": scanner, "output_excerpt": excerpt},
        )

    def save_file_match(self, file_path: str, line_number: int, snippet_masked: str, rule_id: str) -> dict[str, str]:
        if not isinstance(file_path, str) or not file_path.strip():
            raise ValueError("file_path must be a non-empty string")
        if not isinstance(rule_id, str) or not rule_id.strip():
            raise ValueError("rule_id must be a non-empty string")
        try:
            ln = int(line_number)
            if ln < 0:
                ln = 0
        except (TypeError, ValueError):
            ln = 0
        # Ensure snippet is already masked by caller, but mask again defensively
        snippet = mask_text(str(snippet_masked)[:2000]) if snippet_masked else ""
        safe_rule = re.sub(r"[^a-zA-Z0-9._-]", "_", rule_id.strip())[:128]
        return self.save(
            kind="file_match",
            summary=f"{safe_rule} at {file_path.strip()[:1024]}:{ln}",
            payload={
                "file_path": file_path.strip()[:1024],
                "line_number": ln,
                "snippet": snippet,
            },
        )


__all__ = [
    "MAX_BODY_BYTES",
    "MASK",
    "mask_headers",
    "mask_text",
    "mask_body",
    "EvidenceStore",
]
